import { createHash } from 'node:crypto';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { getOpenAIKey, TEXT_MODEL } from '@/lib/openai';

type JsonRecord=Record<string,unknown>;
type ChunkPass='synthesizer'|'critic';
type ConsolidationPass='consolidator'|'critic';
class StructuralOutputError extends Error {}
class ProviderError extends Error { retryable:boolean; constructor(message:string,retryable:boolean){super(message);this.retryable=retryable;} }
const CALL_TIMEOUT_MS=150_000;
const SUBJECTS=['consumer','company','market','expert','regulator','worker','mixed','unclear'] as const;
const MEASUREMENTS=['survey','purchase','usage','consumer_quote','observation','sales','market_data','launch','announcement','operational_change','financial_result','forecast','experiment','other'] as const;

const CHUNK_SYNTH_FORMAT={type:'json_schema',name:'mj_verified_theme_seed_synthesis',strict:true,schema:{type:'object',additionalProperties:false,required:['proposals'],properties:{proposals:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,required:['proposal_key','title','definition','scope_boundary','subject','measurement','support_seed_ids'],properties:{proposal_key:{type:'string'},title:{type:'string'},definition:{type:'string'},scope_boundary:{type:'string'},subject:{type:'string',enum:SUBJECTS},measurement:{type:'string',enum:MEASUREMENTS},support_seed_ids:{type:'array',minItems:1,items:{type:'string'}}}}}}}} as const;
const CHUNK_CRITIC_FORMAT={type:'json_schema',name:'mj_verified_theme_seed_critic',strict:true,schema:{type:'object',additionalProperties:false,required:['proposal_reviews','coverage_complete','missing_seed_ids'],properties:{proposal_reviews:{type:'array',items:{type:'object',additionalProperties:false,required:['proposal_key','verdict','reason'],properties:{proposal_key:{type:'string'},verdict:{type:'string',enum:['approved','rejected','unresolved']},reason:{type:'string'}}}},coverage_complete:{type:'boolean'},missing_seed_ids:{type:'array',items:{type:'string'}}}}} as const;
const CONSOLIDATOR_FORMAT={type:'json_schema',name:'mj_verified_theme_consolidation',strict:true,schema:{type:'object',additionalProperties:false,required:['groups'],properties:{groups:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,required:['group_key','title','definition','inclusion_rule','exclusion_rule','subject','measurement','proposal_ids'],properties:{group_key:{type:'string'},title:{type:'string'},definition:{type:'string'},inclusion_rule:{type:'string'},exclusion_rule:{type:'string'},subject:{type:'string',enum:SUBJECTS},measurement:{type:'string',enum:MEASUREMENTS},proposal_ids:{type:'array',minItems:1,items:{type:'string'}}}}}}}} as const;
const CONSOLIDATION_CRITIC_FORMAT={type:'json_schema',name:'mj_verified_theme_consolidation_critic',strict:true,schema:{type:'object',additionalProperties:false,required:['group_reviews','cross_group_merge_pairs','coverage_complete'],properties:{group_reviews:{type:'array',items:{type:'object',additionalProperties:false,required:['group_key','approved','reason'],properties:{group_key:{type:'string'},approved:{type:'boolean'},reason:{type:'string'}}}},cross_group_merge_pairs:{type:'array',items:{type:'object',additionalProperties:false,required:['group_key_a','group_key_b','reason'],properties:{group_key_a:{type:'string'},group_key_b:{type:'string'},reason:{type:'string'}}}},coverage_complete:{type:'boolean'}}}} as const;

function isRecord(v:unknown):v is JsonRecord{return Boolean(v&&typeof v==='object'&&!Array.isArray(v));}
function text(v:unknown){return v==null?'':String(v).trim();}
function sha256(v:string|Buffer){return createHash('sha256').update(v).digest('hex');}
function errMsg(e:unknown){return e instanceof Error?e.message:isRecord(e)?text(e.message||e.error||e.details):text(e)||'verified theme candidate worker failed';}
function outputText(j:unknown){const x=j as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};if(x?.output_text?.trim())return x.output_text.trim();return(x?.output||[]).flatMap(i=>i.content||[]).map(c=>text(c.text)).filter(Boolean).join('\n').trim();}
function pair(primaryEnv:string,criticEnv:string){const primary=process.env[primaryEnv]?.trim()||TEXT_MODEL;const critic=process.env[criticEnv]?.trim()||(primary==='gpt-4o'?'gpt-4.1':'gpt-4o');if(!primary||!critic||primary===critic)throw new StructuralOutputError(`${primaryEnv} and ${criticEnv} must be configured and distinct.`);return{primary,critic};}
async function callJson(model:string,instructions:string,userText:string,format:unknown,maxTokens=8000){const key=getOpenAIKey();if(!key)throw new StructuralOutputError('OPENAI_API_KEY is not configured.');const promptSha=sha256([model,instructions,userText].join('\n---\n'));const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),CALL_TIMEOUT_MS);try{const res=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},signal:ctl.signal,body:JSON.stringify({model,store:false,max_output_tokens:maxTokens,instructions,input:[{role:'user',content:[{type:'input_text',text:userText}]}],text:{format}})});const raw=await res.text();if(!res.ok)throw new ProviderError(`OpenAI Responses API failed: ${res.status} ${res.statusText} ${raw.slice(0,1800)}`,res.status===408||res.status===409||res.status===429||res.status>=500);const json=JSON.parse(raw) as JsonRecord;const id=text(json.id),out=outputText(json);if(!id||!out)throw new ProviderError('OpenAI theme candidate receipt or output is missing.',true);let value:unknown;try{value=JSON.parse(out);}catch{throw new StructuralOutputError('Theme candidate JSON output invalid.');}return{value,providerResponseId:id,promptSha,responseSha:sha256(raw)};}catch(e){if(e instanceof ProviderError||e instanceof StructuralOutputError)throw e;if(e instanceof Error&&e.name==='AbortError')throw new ProviderError('OpenAI theme candidate request timed out.',true);throw e;}finally{clearTimeout(timer);}}

function chunkInstructions(pass:ChunkPass){return pass==='synthesizer'?[ 'You synthesize local theme proposals from a complete chunk of verified article-level theme seeds.','Use only the supplied seeds. Do not use outside knowledge.','Every seed_id must be covered by at least one proposal. Do not silently discard difficult seeds.','Merge seeds only when they describe the same defensible recurring signal; shared topic alone is insufficient.','Keep scope boundaries explicit so later census can distinguish inclusion from exclusion.','Proposal keys are local opaque labels. Return only JSON.' ].join('\n'):[ 'You are an independent critic of local theme proposals.','Use the supplied verified seeds and the stored proposals.','Review every proposal_key exactly once.','Approve only grounded, coherent proposals; reject or mark unresolved where seeds do not support the proposed scope.','coverage_complete is true only if every supplied seed is represented by the proposal set. missing_seed_ids must list every uncovered seed.','Return only JSON.' ].join('\n');}
function consolidationInstructions(pass:ConsolidationPass){return pass==='consolidator'?[ 'You consolidate all local theme proposals from the verified corpus into final candidate groups.','Use only the supplied proposal summaries.','Assign every proposal_id to exactly one group. Do not omit or duplicate proposals.','Merge only proposals that express the same defensible theme definition and scope; topic similarity alone is insufficient.','Write explicit inclusion and exclusion rules suitable for a later full-corpus census.','Return only JSON.' ].join('\n'):[ 'You are an independent critic of the global proposal grouping.','Use the supplied proposals and proposed groups.','Review every group_key exactly once.','Flag any pair of groups that should actually be merged in cross_group_merge_pairs.','coverage_complete is true only if every proposal appears exactly once and no proposal is omitted.','Approve a group only if its title, definition, inclusion rule, exclusion rule, subject and measurement are coherent with all assigned proposals.','Return only JSON.' ].join('\n');}

function validateChunkSynth(v:unknown,seeds:unknown[]){if(!isRecord(v)||!Array.isArray(v.proposals)||v.proposals.length<1)throw new StructuralOutputError('theme proposals missing');const seedIds=new Set(seeds.map(s=>isRecord(s)?text(s.seed_id):'').filter(Boolean));const covered=new Set<string>();const keys=new Set<string>();for(const raw of v.proposals){if(!isRecord(raw))throw new StructuralOutputError('proposal invalid');const key=text(raw.proposal_key);if(!key||keys.has(key)||text(raw.title).length<2||text(raw.definition).length<8||text(raw.scope_boundary).length<4||!SUBJECTS.includes(text(raw.subject) as never)||!MEASUREMENTS.includes(text(raw.measurement) as never)||!Array.isArray(raw.support_seed_ids)||raw.support_seed_ids.length<1)throw new StructuralOutputError('proposal structure invalid');keys.add(key);for(const idRaw of raw.support_seed_ids){const id=text(idRaw);if(!seedIds.has(id))throw new StructuralOutputError('proposal references unknown seed');covered.add(id);}}if(covered.size!==seedIds.size)throw new StructuralOutputError('seed coverage incomplete');return v;}
function validateChunkCritic(v:unknown,proposals:unknown[],seeds:unknown[]){if(!isRecord(v)||!Array.isArray(v.proposal_reviews)||typeof v.coverage_complete!=='boolean'||!Array.isArray(v.missing_seed_ids))throw new StructuralOutputError('chunk critic schema invalid');const keys=new Set(proposals.map(p=>isRecord(p)?text(p.proposal_key):'').filter(Boolean));const seen=new Set<string>();for(const raw of v.proposal_reviews){if(!isRecord(raw))throw new StructuralOutputError('proposal review invalid');const k=text(raw.proposal_key);if(!keys.has(k)||seen.has(k)||!['approved','rejected','unresolved'].includes(text(raw.verdict))||text(raw.reason).length<4)throw new StructuralOutputError('proposal review set invalid');seen.add(k);}if(seen.size!==keys.size)throw new StructuralOutputError('proposal reviews incomplete');const seedIds=new Set(seeds.map(s=>isRecord(s)?text(s.seed_id):'').filter(Boolean));for(const x of v.missing_seed_ids){if(!seedIds.has(text(x)))throw new StructuralOutputError('critic missing_seed_ids contains unknown seed');}return v;}
function validateGroups(v:unknown,proposals:unknown[]){if(!isRecord(v)||!Array.isArray(v.groups)||v.groups.length<1)throw new StructuralOutputError('consolidation groups missing');const proposalIds=new Set(proposals.map(p=>isRecord(p)?text(p.proposal_id):'').filter(Boolean));const assigned=new Set<string>();const groupKeys=new Set<string>();let assignmentCount=0;for(const raw of v.groups){if(!isRecord(raw))throw new StructuralOutputError('group invalid');const k=text(raw.group_key);if(!k||groupKeys.has(k)||text(raw.title).length<2||text(raw.definition).length<8||text(raw.inclusion_rule).length<4||text(raw.exclusion_rule).length<4||!SUBJECTS.includes(text(raw.subject) as never)||!MEASUREMENTS.includes(text(raw.measurement) as never)||!Array.isArray(raw.proposal_ids)||raw.proposal_ids.length<1)throw new StructuralOutputError('group structure invalid');groupKeys.add(k);for(const x of raw.proposal_ids){const id=text(x);assignmentCount++;if(!proposalIds.has(id)||assigned.has(id))throw new StructuralOutputError('proposal grouping is not a partition');assigned.add(id);}}if(assigned.size!==proposalIds.size||assignmentCount!==proposalIds.size)throw new StructuralOutputError('proposal grouping incomplete');return v;}
function validateGroupCritic(v:unknown,groups:unknown[]){if(!isRecord(v)||!Array.isArray(v.group_reviews)||!Array.isArray(v.cross_group_merge_pairs)||typeof v.coverage_complete!=='boolean')throw new StructuralOutputError('consolidation critic schema invalid');const keys=new Set(groups.map(g=>isRecord(g)?text(g.group_key):'').filter(Boolean));const seen=new Set<string>();for(const raw of v.group_reviews){if(!isRecord(raw))throw new StructuralOutputError('group review invalid');const k=text(raw.group_key);if(!keys.has(k)||seen.has(k)||typeof raw.approved!=='boolean'||text(raw.reason).length<4)throw new StructuralOutputError('group review set invalid');seen.add(k);}if(seen.size!==keys.size)throw new StructuralOutputError('group reviews incomplete');for(const raw of v.cross_group_merge_pairs){if(!isRecord(raw)||!keys.has(text(raw.group_key_a))||!keys.has(text(raw.group_key_b))||text(raw.group_key_a)===text(raw.group_key_b)||text(raw.reason).length<4)throw new StructuralOutputError('cross-group merge pair invalid');}return v;}

async function createRun(){const {data,error}=await supabaseAdmin.rpc('create_verified_theme_analysis_run_v7',{p_seed_chunk_size:40});if(error){const m=errMsg(error);if(m.includes('verified_theme_v7_review_gate_required'))return null;throw error;}return text(data);}
async function claimChunk(){const {data,error}=await supabaseAdmin.rpc('claim_verified_theme_seed_chunk_job_v7',{p_lease_seconds:240});if(error)throw error;const r=Array.isArray(data)&&isRecord(data[0])?data[0]:null;if(!r)return null;const job={id:text(r.id),runId:text(r.analysis_run_id),pass:text(r.active_pass_kind) as ChunkPass,token:text(r.lease_token)};if(!job.id||!job.runId||!job.token||!['synthesizer','critic'].includes(job.pass))throw new StructuralOutputError('claimed seed chunk invalid');return job;}
async function claimConsolidation(){const {data,error}=await supabaseAdmin.rpc('claim_verified_theme_consolidation_job_v7',{p_lease_seconds:240});if(error)throw error;const r=Array.isArray(data)&&isRecord(data[0])?data[0]:null;if(!r)return null;const job={id:text(r.id),runId:text(r.analysis_run_id),pass:text(r.active_pass_kind) as ConsolidationPass,token:text(r.lease_token)};if(!job.id||!job.runId||!job.token||!['consolidator','critic'].includes(job.pass))throw new StructuralOutputError('claimed consolidation invalid');return job;}
async function chunkInput(job:NonNullable<Awaited<ReturnType<typeof claimChunk>>>){const {data,error}=await supabaseAdmin.rpc('get_verified_theme_seed_chunk_input_v7',{p_job_id:job.id,p_lease_token:job.token});if(error)throw error;if(!isRecord(data)||!Array.isArray(data.seeds))throw new StructuralOutputError('seed chunk input malformed');return{seeds:data.seeds,proposals:Array.isArray(data.proposals)?data.proposals:[]};}
async function consolidationInput(job:NonNullable<Awaited<ReturnType<typeof claimConsolidation>>>){const {data,error}=await supabaseAdmin.rpc('get_verified_theme_consolidation_input_v7',{p_job_id:job.id,p_lease_token:job.token});if(error)throw error;if(!isRecord(data)||!Array.isArray(data.proposals))throw new StructuralOutputError('consolidation input malformed');return{proposals:data.proposals,groups:Array.isArray(data.groups)?data.groups:[]};}
async function storeChunk(job:NonNullable<Awaited<ReturnType<typeof claimChunk>>>,model:string,r:Awaited<ReturnType<typeof callJson>>,result:unknown){const {data,error}=await supabaseAdmin.rpc('store_verified_theme_seed_chunk_pass_v7',{p_job_id:job.id,p_lease_token:job.token,p_pass_kind:job.pass,p_model:model,p_provider_response_id:r.providerResponseId,p_prompt_sha256:r.promptSha,p_response_sha256:r.responseSha,p_result:result});if(error)throw error;return data;}
async function storeConsolidation(job:NonNullable<Awaited<ReturnType<typeof claimConsolidation>>>,model:string,r:Awaited<ReturnType<typeof callJson>>,result:unknown){const {data,error}=await supabaseAdmin.rpc('store_verified_theme_consolidation_pass_v7',{p_job_id:job.id,p_lease_token:job.token,p_pass_kind:job.pass,p_model:model,p_provider_response_id:r.providerResponseId,p_prompt_sha256:r.promptSha,p_response_sha256:r.responseSha,p_result:result});if(error)throw error;return data;}
async function failChunk(job:NonNullable<Awaited<ReturnType<typeof claimChunk>>>,e:unknown){const {data,error}=await supabaseAdmin.rpc('fail_verified_theme_seed_chunk_job_v7',{p_job_id:job.id,p_lease_token:job.token,p_error:errMsg(e),p_retryable:e instanceof ProviderError?e.retryable:false});if(error)throw error;return data;}
async function failConsolidation(job:NonNullable<Awaited<ReturnType<typeof claimConsolidation>>>,e:unknown){const {data,error}=await supabaseAdmin.rpc('fail_verified_theme_consolidation_job_v7',{p_job_id:job.id,p_lease_token:job.token,p_error:errMsg(e),p_retryable:e instanceof ProviderError?e.retryable:false});if(error)throw error;return data;}

export async function getVerifiedThemeCandidateStatus(){const [{data:gate,error:ge},{data:run,error:re}]=await Promise.all([supabaseAdmin.from('verified_theme_candidate_gate_v7').select('*').maybeSingle(),supabaseAdmin.from('verified_theme_analysis_runs_v7').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(ge)throw ge;if(re)throw re;let chunkJobs:Record<string,number>={},consolidationJobs:Record<string,number>={};if(run?.id){const [{data:c,error:ce},{data:g,error:gne}]=await Promise.all([supabaseAdmin.from('verified_theme_seed_chunk_jobs_v7').select('status').eq('analysis_run_id',run.id),supabaseAdmin.from('verified_theme_consolidation_jobs_v7').select('status').eq('analysis_run_id',run.id)]);if(ce)throw ce;if(gne)throw gne;for(const x of c||[]){const s=text(x.status)||'unknown';chunkJobs[s]=(chunkJobs[s]||0)+1;}for(const x of g||[]){const s=text(x.status)||'unknown';consolidationJobs[s]=(consolidationJobs[s]||0)+1;}}return{gate,run,seed_chunk_jobs:chunkJobs,consolidation_jobs:consolidationJobs};}

export async function runVerifiedThemeCandidateWorkerStep(){const runId=await createRun();if(!runId)return{stage:'blocked',reason:'verified_article_review_required',external_calls:0};const {data:run,error:runErr}=await supabaseAdmin.from('verified_theme_analysis_runs_v7').select('*').eq('id',runId).single();if(runErr)throw runErr;if(run.status==='candidates_ready')return{stage:'candidates_ready',run_id:runId,candidate_set_fingerprint:run.candidate_set_fingerprint,external_calls:0};if(run.status==='needs_review')return{stage:'needs_review',run_id:runId,reason:run.error_message,external_calls:0};
  const chunk=await claimChunk();if(chunk){let calls=0;try{const input=await chunkInput(chunk);const ms=pair('OPENAI_THEME_SYNTHESIZER_MODEL','OPENAI_THEME_SEED_CRITIC_MODEL');const model=chunk.pass==='synthesizer'?ms.primary:ms.critic;const user=JSON.stringify(chunk.pass==='synthesizer'?{task:'synthesize_verified_theme_seed_chunk',seeds:input.seeds}:{task:'criticize_verified_theme_seed_chunk',seeds:input.seeds,proposals:input.proposals});calls=1;const r=await callJson(model,chunkInstructions(chunk.pass),user,chunk.pass==='synthesizer'?CHUNK_SYNTH_FORMAT:CHUNK_CRITIC_FORMAT,9000);const result=chunk.pass==='synthesizer'?validateChunkSynth(r.value,input.seeds):validateChunkCritic(r.value,input.proposals,input.seeds);const saved=await storeChunk(chunk,model,r,result);return{stage:'theme_seed_chunk_pass',run_id:chunk.runId,job_id:chunk.id,pass_kind:chunk.pass,result:saved,external_calls:calls};}catch(e){const saved=await failChunk(chunk,e);return{stage:'theme_seed_chunk_failed',run_id:chunk.runId,job_id:chunk.id,pass_kind:chunk.pass,error:errMsg(e),result:saved,external_calls:calls};}}
  const {data:consolidationId,error:prepErr}=await supabaseAdmin.rpc('prepare_verified_theme_consolidation_v7',{p_analysis_run_id:runId});if(prepErr)throw prepErr;const consolidation=await claimConsolidation();if(consolidation){let calls=0;try{const input=await consolidationInput(consolidation);const ms=pair('OPENAI_THEME_CONSOLIDATOR_MODEL','OPENAI_THEME_CONSOLIDATION_CRITIC_MODEL');const model=consolidation.pass==='consolidator'?ms.primary:ms.critic;const user=JSON.stringify(consolidation.pass==='consolidator'?{task:'consolidate_all_verified_theme_proposals',proposals:input.proposals}:{task:'criticize_verified_theme_consolidation',proposals:input.proposals,groups:input.groups});calls=1;const r=await callJson(model,consolidationInstructions(consolidation.pass),user,consolidation.pass==='consolidator'?CONSOLIDATOR_FORMAT:CONSOLIDATION_CRITIC_FORMAT,12000);const result=consolidation.pass==='consolidator'?validateGroups(r.value,input.proposals):validateGroupCritic(r.value,input.groups);const saved=await storeConsolidation(consolidation,model,r,result);return{stage:'theme_consolidation_pass',run_id:consolidation.runId,job_id:consolidation.id,pass_kind:consolidation.pass,result:saved,external_calls:calls};}catch(e){const saved=await failConsolidation(consolidation,e);return{stage:'theme_consolidation_failed',run_id:consolidation.runId,job_id:consolidation.id,pass_kind:consolidation.pass,error:errMsg(e),result:saved,external_calls:calls};}}
  const {data:fresh,error:freshErr}=await supabaseAdmin.from('verified_theme_analysis_runs_v7').select('*').eq('id',runId).single();if(freshErr)throw freshErr;return{stage:fresh.status==='candidates_ready'?'candidates_ready':'idle',run_id:runId,consolidation_job_id:consolidationId||null,status:fresh.status,external_calls:0};
}
