import { createHash } from 'node:crypto';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { getOpenAIKey, TEXT_MODEL } from '@/lib/openai';

type JsonRecord=Record<string,unknown>;
type PassKind='generator'|'critic';
class StructuralOutputError extends Error {}
class ProviderError extends Error{retryable:boolean;constructor(message:string,retryable:boolean){super(message);this.retryable=retryable;}}
const CALL_TIMEOUT_MS=150_000;
const DIGIT_RE=/[0-9０-９]/;
const NOTE_FORMAT={type:'json_schema',name:'mj_verified_theme_note',strict:true,schema:{type:'object',additionalProperties:false,required:['interpretation','trajectory_interpretation','limitation','evidence_article_ids'],properties:{interpretation:{type:'string'},trajectory_interpretation:{type:'string'},limitation:{type:'string'},evidence_article_ids:{type:'array',items:{type:'string'}}}}} as const;
const NOTE_CRITIC_FORMAT={type:'json_schema',name:'mj_verified_theme_note_critic',strict:true,schema:{type:'object',additionalProperties:false,required:['approved','evidence_supported','trend_consistent','limitation_adequate','overclaim_risk','reason'],properties:{approved:{type:'boolean'},evidence_supported:{type:'boolean'},trend_consistent:{type:'boolean'},limitation_adequate:{type:'boolean'},overclaim_risk:{type:'boolean'},reason:{type:'string'}}}} as const;
const FINAL_FORMAT={type:'json_schema',name:'mj_verified_theme_report_final',strict:true,schema:{type:'object',additionalProperties:false,required:['executive_summary','major_theme_ids','coverage_candidate_ids','cross_theme_observations'],properties:{executive_summary:{type:'string'},major_theme_ids:{type:'array',items:{type:'string'}},coverage_candidate_ids:{type:'array',items:{type:'string'}},cross_theme_observations:{type:'array',items:{type:'object',additionalProperties:false,required:['candidate_ids','statement','limitation'],properties:{candidate_ids:{type:'array',minItems:2,items:{type:'string'}},statement:{type:'string'},limitation:{type:'string'}}}}}}} as const;
const FINAL_CRITIC_FORMAT={type:'json_schema',name:'mj_verified_theme_report_final_critic',strict:true,schema:{type:'object',additionalProperties:false,required:['approved','coverage_complete','metrics_consistent','evidence_scope_valid','overclaim_risk','reason'],properties:{approved:{type:'boolean'},coverage_complete:{type:'boolean'},metrics_consistent:{type:'boolean'},evidence_scope_valid:{type:'boolean'},overclaim_risk:{type:'boolean'},reason:{type:'string'}}}} as const;
function isRecord(v:unknown):v is JsonRecord{return Boolean(v&&typeof v==='object'&&!Array.isArray(v));}
function text(v:unknown){return v==null?'':String(v).trim();}
function sha256(v:string|Buffer){return createHash('sha256').update(v).digest('hex');}
function errMsg(e:unknown){return e instanceof Error?e.message:isRecord(e)?text(e.message||e.error||e.details):text(e)||'verified theme report worker failed';}
function outputText(j:unknown){const x=j as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};if(x?.output_text?.trim())return x.output_text.trim();return(x?.output||[]).flatMap(i=>i.content||[]).map(c=>text(c.text)).filter(Boolean).join('\n').trim();}
function pair(primaryEnv:string,criticEnv:string){const primary=process.env[primaryEnv]?.trim()||TEXT_MODEL;const critic=process.env[criticEnv]?.trim()||(primary==='gpt-4o'?'gpt-4.1':'gpt-4o');if(!primary||!critic||primary===critic)throw new StructuralOutputError(`${primaryEnv} and ${criticEnv} must be configured and distinct.`);return{primary,critic};}
async function callJson(model:string,instructions:string,userText:string,format:unknown,maxTokens:number){const key=getOpenAIKey();if(!key)throw new StructuralOutputError('OPENAI_API_KEY is not configured.');const promptSha=sha256([model,instructions,userText].join('\n---\n'));const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),CALL_TIMEOUT_MS);try{const res=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},signal:ctl.signal,body:JSON.stringify({model,store:false,max_output_tokens:maxTokens,instructions,input:[{role:'user',content:[{type:'input_text',text:userText}]}],text:{format}})});const raw=await res.text();if(!res.ok)throw new ProviderError(`OpenAI Responses API failed: ${res.status} ${res.statusText} ${raw.slice(0,1800)}`,res.status===408||res.status===409||res.status===429||res.status>=500);const json=JSON.parse(raw) as JsonRecord;const id=text(json.id),out=outputText(json);if(!id||!out)throw new ProviderError('OpenAI report receipt or output is missing.',true);let value:unknown;try{value=JSON.parse(out);}catch{throw new StructuralOutputError('Report JSON output invalid.');}return{value,providerResponseId:id,promptSha,responseSha:sha256(raw)};}catch(e){if(e instanceof ProviderError||e instanceof StructuralOutputError)throw e;if(e instanceof Error&&e.name==='AbortError')throw new ProviderError('OpenAI report request timed out.',true);throw e;}finally{clearTimeout(timer);}}
function noteInstructions(pass:PassKind){return pass==='generator'?[ 'You write one evidence-bounded theme note for a verified newspaper corpus.','Use only the supplied deterministic DB metric row and deterministic evidence articles.','The quantitative metric fields are authoritative DB calculations. Do not reproduce, round, infer, or generate any numeric value in your prose.','Do not write numerals, percentages, counts, dates, rankings, or quantitative estimates in interpretation, trajectory_interpretation, or limitation.','Interpretation should explain what the evidence means qualitatively. trajectory_interpretation should describe direction cautiously and only when consistent with the DB metric. limitation must state the strongest material limitation.','evidence_article_ids may contain only article IDs from deterministic_evidence. When support exists, cite at least one.','Return only JSON.' ].join('\n'):[ 'You independently audit one generated theme note against the same authoritative DB metric and deterministic evidence.','Approve only if the prose is fully evidence-supported, qualitatively consistent with the DB trend fields, contains an adequate limitation, does not overclaim, and cites only deterministic evidence IDs.','Do not repair the note. Reject it if material problems remain.','Return only JSON.' ].join('\n');}
function finalInstructions(pass:PassKind){return pass==='generator'?[ 'You synthesize the final qualitative report from authoritative DB theme metrics and already verified theme notes.','All quantitative values belong to the structured DB metrics, not to generated prose. Do not reproduce, round, infer, or generate numeric values in executive_summary, cross-theme statements, or limitations.','Do not write numerals, percentages, counts, dates, rankings, or quantitative estimates in free-form prose.','coverage_candidate_ids must contain every supplied candidate_id exactly once.','major_theme_ids may contain only candidates with actual support in the supplied DB metrics. Select them based on the evidence and metrics without inventing thresholds.','Cross-theme observations must reference at least two candidate IDs and be supported by the supplied notes/metrics; state a limitation for each observation.','Return only JSON.' ].join('\n'):[ 'You independently audit the final generated synthesis against all authoritative DB metrics and verified theme notes.','Approve only if every candidate is covered, qualitative claims are consistent with DB metrics, evidence scope is valid, and there is no material overclaim.','Do not repair the synthesis. Reject it if material problems remain.','Return only JSON.' ].join('\n');}
function validateNote(v:unknown,metric:unknown,evidence:unknown[]){if(!isRecord(v)||text(v.interpretation).length<8||text(v.trajectory_interpretation).length<4||text(v.limitation).length<4||!Array.isArray(v.evidence_article_ids))throw new StructuralOutputError('theme note generator schema invalid');if(DIGIT_RE.test(text(v.interpretation))||DIGIT_RE.test(text(v.trajectory_interpretation))||DIGIT_RE.test(text(v.limitation)))throw new StructuralOutputError('numeric prose forbidden in theme note');const allowed=new Set(evidence.map(e=>isRecord(e)?text(e.article_id):'').filter(Boolean));const seen=new Set<string>();for(const x of v.evidence_article_ids){const id=text(x);if(!allowed.has(id)||seen.has(id))throw new StructuralOutputError('theme note evidence IDs invalid');seen.add(id);}const support=isRecord(metric)?Number(metric.support_article_count||0):0;if(support>0&&seen.size===0)throw new StructuralOutputError('theme note evidence required');return v;}
function validateNoteCritic(v:unknown){if(!isRecord(v)||typeof v.approved!=='boolean'||typeof v.evidence_supported!=='boolean'||typeof v.trend_consistent!=='boolean'||typeof v.limitation_adequate!=='boolean'||typeof v.overclaim_risk!=='boolean'||text(v.reason).length<4)throw new StructuralOutputError('theme note critic invalid');return v;}
function validateFinal(v:unknown,metrics:unknown[]){if(!isRecord(v)||text(v.executive_summary).length<12||!Array.isArray(v.major_theme_ids)||!Array.isArray(v.coverage_candidate_ids)||!Array.isArray(v.cross_theme_observations))throw new StructuralOutputError('final report generator schema invalid');if(DIGIT_RE.test(text(v.executive_summary)))throw new StructuralOutputError('numeric prose forbidden in executive summary');const candidateIds=new Set(metrics.map(m=>isRecord(m)?text(m.candidate_id):'').filter(Boolean));const supportIds=new Set(metrics.filter(m=>isRecord(m)&&Number(m.support_article_count||0)>0).map(m=>text((m as JsonRecord).candidate_id)));const coverage=new Set<string>();for(const x of v.coverage_candidate_ids){const id=text(x);if(!candidateIds.has(id)||coverage.has(id))throw new StructuralOutputError('coverage candidate IDs invalid');coverage.add(id);}if(coverage.size!==candidateIds.size)throw new StructuralOutputError('coverage candidate set incomplete');const majors=new Set<string>();for(const x of v.major_theme_ids){const id=text(x);if(!supportIds.has(id)||majors.has(id))throw new StructuralOutputError('major theme IDs invalid');majors.add(id);}for(const raw of v.cross_theme_observations){if(!isRecord(raw)||!Array.isArray(raw.candidate_ids)||raw.candidate_ids.length<2||text(raw.statement).length<8||text(raw.limitation).length<4||DIGIT_RE.test(text(raw.statement))||DIGIT_RE.test(text(raw.limitation)))throw new StructuralOutputError('cross-theme observation invalid');const local=new Set<string>();for(const x of raw.candidate_ids){const id=text(x);if(!candidateIds.has(id)||local.has(id))throw new StructuralOutputError('cross-theme candidate IDs invalid');local.add(id);}}return v;}
function validateFinalCritic(v:unknown){if(!isRecord(v)||typeof v.approved!=='boolean'||typeof v.coverage_complete!=='boolean'||typeof v.metrics_consistent!=='boolean'||typeof v.evidence_scope_valid!=='boolean'||typeof v.overclaim_risk!=='boolean'||text(v.reason).length<4)throw new StructuralOutputError('final report critic invalid');return v;}
async function ensureRun(){const {data:gate,error:ge}=await supabaseAdmin.from('verified_theme_analysis_gate_v8').select('*').maybeSingle();if(ge)throw ge;if(!gate||gate.analysis_gate!=='passed')return null;const {data,error}=await supabaseAdmin.rpc('create_verified_theme_report_run_v8');if(error)throw error;return text(data);}
async function claimNote(){const {data,error}=await supabaseAdmin.rpc('claim_verified_theme_report_note_job_v8',{p_lease_seconds:240});if(error)throw error;const r=Array.isArray(data)&&isRecord(data[0])?data[0]:null;if(!r)return null;const job={id:text(r.id),runId:text(r.run_id),candidateId:text(r.candidate_id),pass:text(r.active_pass_kind) as PassKind,token:text(r.lease_token)};if(!job.id||!job.runId||!job.candidateId||!job.token||!['generator','critic'].includes(job.pass))throw new StructuralOutputError('claimed report note job invalid');return job;}
async function claimFinal(){const {data,error}=await supabaseAdmin.rpc('claim_verified_theme_report_final_job_v8',{p_lease_seconds:240});if(error)throw error;const r=Array.isArray(data)&&isRecord(data[0])?data[0]:null;if(!r)return null;const job={id:text(r.id),runId:text(r.run_id),pass:text(r.active_pass_kind) as PassKind,token:text(r.lease_token)};if(!job.id||!job.runId||!job.token||!['generator','critic'].includes(job.pass))throw new StructuralOutputError('claimed final report job invalid');return job;}
async function noteInput(job:NonNullable<Awaited<ReturnType<typeof claimNote>>>){const {data,error}=await supabaseAdmin.rpc('get_verified_theme_report_note_input_v8',{p_job_id:job.id,p_lease_token:job.token});if(error)throw error;if(!isRecord(data)||!isRecord(data.metric)||!Array.isArray(data.deterministic_evidence))throw new StructuralOutputError('report note input malformed');return{metric:data.metric,evidence:data.deterministic_evidence,generator:data.generator_output};}
async function finalInput(job:NonNullable<Awaited<ReturnType<typeof claimFinal>>>){const {data,error}=await supabaseAdmin.rpc('get_verified_theme_report_final_input_v8',{p_job_id:job.id,p_lease_token:job.token});if(error)throw error;if(!isRecord(data)||!Array.isArray(data.theme_metrics)||!Array.isArray(data.theme_notes))throw new StructuralOutputError('final report input malformed');return{metrics:data.theme_metrics,notes:data.theme_notes,generator:data.generator_output};}
async function storeNote(job:NonNullable<Awaited<ReturnType<typeof claimNote>>>,model:string,r:Awaited<ReturnType<typeof callJson>>,result:unknown){const {data,error}=await supabaseAdmin.rpc('store_verified_theme_report_note_pass_v8',{p_job_id:job.id,p_lease_token:job.token,p_pass_kind:job.pass,p_model:model,p_provider_response_id:r.providerResponseId,p_prompt_sha256:r.promptSha,p_response_sha256:r.responseSha,p_result:result});if(error)throw error;return data;}
async function storeFinal(job:NonNullable<Awaited<ReturnType<typeof claimFinal>>>,model:string,r:Awaited<ReturnType<typeof callJson>>,result:unknown){const {data,error}=await supabaseAdmin.rpc('store_verified_theme_report_final_pass_v8',{p_job_id:job.id,p_lease_token:job.token,p_pass_kind:job.pass,p_model:model,p_provider_response_id:r.providerResponseId,p_prompt_sha256:r.promptSha,p_response_sha256:r.responseSha,p_result:result});if(error)throw error;return data;}
async function failNote(job:NonNullable<Awaited<ReturnType<typeof claimNote>>>,e:unknown){const {data,error}=await supabaseAdmin.rpc('fail_verified_theme_report_note_job_v8',{p_job_id:job.id,p_lease_token:job.token,p_error:errMsg(e),p_retryable:e instanceof ProviderError?e.retryable:false});if(error)throw error;return data;}
async function failFinal(job:NonNullable<Awaited<ReturnType<typeof claimFinal>>>,e:unknown){const {data,error}=await supabaseAdmin.rpc('fail_verified_theme_report_final_job_v8',{p_job_id:job.id,p_lease_token:job.token,p_error:errMsg(e),p_retryable:e instanceof ProviderError?e.retryable:false});if(error)throw error;return data;}
export async function getVerifiedThemeReportStatus(){const [{data:gate,error:ge},{data:run,error:re}]=await Promise.all([supabaseAdmin.from('verified_theme_report_gate_v8').select('*').maybeSingle(),supabaseAdmin.from('verified_theme_report_runs_v8').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(ge)throw ge;if(re)throw re;let noteJobs:Record<string,number>={},finalJobs:Record<string,number>={};if(run?.id){const [{data:n,error:ne},{data:f,error:fe}]=await Promise.all([supabaseAdmin.from('verified_theme_report_note_jobs_v8').select('status').eq('run_id',run.id),supabaseAdmin.from('verified_theme_report_final_jobs_v8').select('status').eq('run_id',run.id)]);if(ne)throw ne;if(fe)throw fe;for(const x of n||[]){const s=text(x.status)||'unknown';noteJobs[s]=(noteJobs[s]||0)+1;}for(const x of f||[]){const s=text(x.status)||'unknown';finalJobs[s]=(finalJobs[s]||0)+1;}}return{gate,run,note_jobs:noteJobs,final_jobs:finalJobs};}
export async function runVerifiedThemeReportWorkerStep(){const runId=await ensureRun();if(!runId)return{stage:'blocked',reason:'verified_theme_analysis_proof_required',external_calls:0};const {data:run,error:runErr}=await supabaseAdmin.from('verified_theme_report_runs_v8').select('*').eq('id',runId).single();if(runErr)throw runErr;if(run.status==='completed')return{stage:'report_completed',run_id:runId,external_calls:0};if(run.status==='needs_review'||run.status==='failed')return{stage:run.status,run_id:runId,reason:run.error_message,external_calls:0};
  const note=await claimNote();if(note){let calls=0;try{const input=await noteInput(note);const ms=pair('OPENAI_THEME_REPORT_NOTE_MODEL','OPENAI_THEME_REPORT_NOTE_CRITIC_MODEL');const model=note.pass==='generator'?ms.primary:ms.critic;const user=JSON.stringify(note.pass==='generator'?{task:'write_verified_theme_note',metric:input.metric,deterministic_evidence:input.evidence}:{task:'criticize_verified_theme_note',metric:input.metric,deterministic_evidence:input.evidence,generator_output:input.generator});calls=1;const r=await callJson(model,noteInstructions(note.pass),user,note.pass==='generator'?NOTE_FORMAT:NOTE_CRITIC_FORMAT,5000);const result=note.pass==='generator'?validateNote(r.value,input.metric,input.evidence):validateNoteCritic(r.value);const saved=await storeNote(note,model,r,result);return{stage:'theme_report_note_pass',run_id:note.runId,candidate_id:note.candidateId,job_id:note.id,pass_kind:note.pass,result:saved,external_calls:calls};}catch(e){const saved=await failNote(note,e);return{stage:'theme_report_note_failed',run_id:note.runId,candidate_id:note.candidateId,job_id:note.id,pass_kind:note.pass,error:errMsg(e),result:saved,external_calls:calls};}}
  const {data:finalId,error:prepErr}=await supabaseAdmin.rpc('prepare_verified_theme_report_final_v8',{p_run_id:runId});if(prepErr)throw prepErr;const final=await claimFinal();if(final){let calls=0;try{const input=await finalInput(final);const ms=pair('OPENAI_THEME_REPORT_FINAL_MODEL','OPENAI_THEME_REPORT_FINAL_CRITIC_MODEL');const model=final.pass==='generator'?ms.primary:ms.critic;const user=JSON.stringify(final.pass==='generator'?{task:'synthesize_verified_theme_report',theme_metrics:input.metrics,theme_notes:input.notes}:{task:'criticize_verified_theme_report',theme_metrics:input.metrics,theme_notes:input.notes,generator_output:input.generator});calls=1;const r=await callJson(model,finalInstructions(final.pass),user,final.pass==='generator'?FINAL_FORMAT:FINAL_CRITIC_FORMAT,8000);const result=final.pass==='generator'?validateFinal(r.value,input.metrics):validateFinalCritic(r.value);const saved=await storeFinal(final,model,r,result);return{stage:'theme_report_final_pass',run_id:final.runId,job_id:final.id,pass_kind:final.pass,result:saved,external_calls:calls};}catch(e){const saved=await failFinal(final,e);return{stage:'theme_report_final_failed',run_id:final.runId,job_id:final.id,pass_kind:final.pass,error:errMsg(e),result:saved,external_calls:calls};}}
  const {data:fresh,error:freshErr}=await supabaseAdmin.from('verified_theme_report_runs_v8').select('*').eq('id',runId).single();if(freshErr)throw freshErr;return{stage:fresh.status==='completed'?'report_completed':'idle',run_id:runId,final_job_id:finalId||null,status:fresh.status,external_calls:0};
}
