import { createHash } from 'node:crypto';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { getOpenAIKey, TEXT_MODEL } from '@/lib/openai';

type JsonRecord=Record<string,unknown>;
type PassKind='mapper'|'critic';
class StructuralOutputError extends Error {}
class ProviderError extends Error{retryable:boolean;constructor(message:string,retryable:boolean){super(message);this.retryable=retryable;}}
const CALL_TIMEOUT_MS=150_000;
const RESPONSE_FORMAT={type:'json_schema',name:'mj_verified_theme_census',strict:true,schema:{type:'object',additionalProperties:false,required:['articles'],properties:{articles:{type:'array',items:{type:'object',additionalProperties:false,required:['article_id','evaluation_complete','matches'],properties:{article_id:{type:'string'},evaluation_complete:{type:'boolean'},matches:{type:'array',items:{type:'object',additionalProperties:false,required:['candidate_id','confidence','source_anchor','reason'],properties:{candidate_id:{type:'string'},confidence:{type:'number',minimum:0,maximum:1},source_anchor:{type:'string'},reason:{type:'string'}}}}}}}}}} as const;
function isRecord(v:unknown):v is JsonRecord{return Boolean(v&&typeof v==='object'&&!Array.isArray(v));}
function text(v:unknown){return v==null?'':String(v).trim();}
function sha256(v:string|Buffer){return createHash('sha256').update(v).digest('hex');}
function errMsg(e:unknown){return e instanceof Error?e.message:isRecord(e)?text(e.message||e.error||e.details):text(e)||'verified theme census worker failed';}
function outputText(j:unknown){const x=j as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};if(x?.output_text?.trim())return x.output_text.trim();return(x?.output||[]).flatMap(i=>i.content||[]).map(c=>text(c.text)).filter(Boolean).join('\n').trim();}
function models(){const mapper=process.env.OPENAI_THEME_CENSUS_MAPPER_MODEL?.trim()||TEXT_MODEL;const critic=process.env.OPENAI_THEME_CENSUS_CRITIC_MODEL?.trim()||(mapper==='gpt-4o'?'gpt-4.1':'gpt-4o');if(!mapper||!critic||mapper===critic)throw new StructuralOutputError('Theme census mapper and critic models must be configured and distinct.');return{mapper,critic};}
async function callJson(model:string,instructions:string,userText:string){const key=getOpenAIKey();if(!key)throw new StructuralOutputError('OPENAI_API_KEY is not configured.');const promptSha=sha256([model,instructions,userText].join('\n---\n'));const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),CALL_TIMEOUT_MS);try{const res=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},signal:ctl.signal,body:JSON.stringify({model,store:false,max_output_tokens:12000,instructions,input:[{role:'user',content:[{type:'input_text',text:userText}]}],text:{format:RESPONSE_FORMAT}})});const raw=await res.text();if(!res.ok)throw new ProviderError(`OpenAI Responses API failed: ${res.status} ${res.statusText} ${raw.slice(0,1800)}`,res.status===408||res.status===409||res.status===429||res.status>=500);const json=JSON.parse(raw) as JsonRecord;const id=text(json.id),out=outputText(json);if(!id||!out)throw new ProviderError('OpenAI census receipt or output is missing.',true);let value:unknown;try{value=JSON.parse(out);}catch{throw new StructuralOutputError('Census JSON output invalid.');}return{value,providerResponseId:id,promptSha,responseSha:sha256(raw)};}catch(e){if(e instanceof ProviderError||e instanceof StructuralOutputError)throw e;if(e instanceof Error&&e.name==='AbortError')throw new ProviderError('OpenAI census request timed out.',true);throw e;}finally{clearTimeout(timer);}}
function instructions(pass:PassKind){return [pass==='mapper'?'You are the first independent full-corpus theme mapper.':'You are an independent second full-corpus theme critic. Make your own mapping from the same evidence; do not assume another mapper exists.','You receive the complete current theme candidate catalog and a batch of articles represented only by verified crop OCR text.','Evaluate every candidate against every article in the batch. Return exactly one article row for every supplied article_id.','Return only candidates that are directly and materially supported by the article according to the candidate inclusion/exclusion rules. Topic similarity is not enough.','Every returned source_anchor must be an exact contiguous substring of that article text.','Only return a match with confidence at least 0.80. If uncertain, omit the match rather than forcing it.','Set evaluation_complete=true only after considering the entire candidate catalog for that article.','Outside knowledge, embeddings, category labels, headlines, and prior pass outputs are forbidden.','Return only JSON.'].join('\n');}
function validate(v:unknown,articles:unknown[],candidates:unknown[]){if(!isRecord(v)||!Array.isArray(v.articles))throw new StructuralOutputError('census articles missing');const bodies=new Map<string,string>();for(const a of articles){if(!isRecord(a))throw new StructuralOutputError('census input article invalid');bodies.set(text(a.article_id),text(a.verified_crop_ocr_text));}const candidateIds=new Set(candidates.map(c=>isRecord(c)?text(c.candidate_id):'').filter(Boolean));if(v.articles.length!==bodies.size)throw new StructuralOutputError('census article row count mismatch');const seenArticles=new Set<string>();for(const raw of v.articles){if(!isRecord(raw))throw new StructuralOutputError('census article result invalid');const id=text(raw.article_id),body=bodies.get(id);if(!body||seenArticles.has(id)||raw.evaluation_complete!==true||!Array.isArray(raw.matches))throw new StructuralOutputError('census article result set invalid');seenArticles.add(id);const seenCandidates=new Set<string>();for(const m of raw.matches){if(!isRecord(m))throw new StructuralOutputError('census match invalid');const cid=text(m.candidate_id),conf=Number(m.confidence),anchor=text(m.source_anchor);if(!candidateIds.has(cid)||seenCandidates.has(cid)||!Number.isFinite(conf)||conf<0.80||conf>1||anchor.length<6||!body.toLocaleLowerCase().includes(anchor.toLocaleLowerCase())||text(m.reason).length<4)throw new StructuralOutputError('census match invalid');seenCandidates.add(cid);}}if(seenArticles.size!==bodies.size)throw new StructuralOutputError('census article set incomplete');return v;}
async function enqueue(){const {data,error}=await supabaseAdmin.rpc('enqueue_verified_theme_census_v7',{p_article_batch_size:10});if(error){const m=errMsg(error);if(m.includes('verified_census_v7_candidate_gate_required'))return{blocked:true,count:0};throw error;}return{blocked:false,count:Number(data||0)};}
async function claim(){const {data,error}=await supabaseAdmin.rpc('claim_verified_theme_census_batch_v7',{p_lease_seconds:240});if(error)throw error;const r=Array.isArray(data)&&isRecord(data[0])?data[0]:null;if(!r)return null;const job={id:text(r.id),runId:text(r.analysis_run_id),pass:text(r.active_pass_kind) as PassKind,token:text(r.lease_token)};if(!job.id||!job.runId||!job.token||!['mapper','critic'].includes(job.pass))throw new StructuralOutputError('claimed census batch invalid');return job;}
async function getInput(job:NonNullable<Awaited<ReturnType<typeof claim>>>){const {data,error}=await supabaseAdmin.rpc('get_verified_theme_census_input_v7',{p_batch_id:job.id,p_lease_token:job.token});if(error)throw error;if(!isRecord(data)||!Array.isArray(data.articles)||!Array.isArray(data.candidates)||data.articles.length<1||data.candidates.length<1)throw new StructuralOutputError('census input malformed');return{articles:data.articles,candidates:data.candidates};}
async function store(job:NonNullable<Awaited<ReturnType<typeof claim>>>,model:string,r:Awaited<ReturnType<typeof callJson>>,result:unknown){const {data,error}=await supabaseAdmin.rpc('store_verified_theme_census_pass_v7',{p_batch_id:job.id,p_lease_token:job.token,p_pass_kind:job.pass,p_model:model,p_provider_response_id:r.providerResponseId,p_prompt_sha256:r.promptSha,p_response_sha256:r.responseSha,p_result:result});if(error)throw error;return data;}
async function fail(job:NonNullable<Awaited<ReturnType<typeof claim>>>,e:unknown){const {data,error}=await supabaseAdmin.rpc('fail_verified_theme_census_batch_v7',{p_batch_id:job.id,p_lease_token:job.token,p_error:errMsg(e),p_retryable:e instanceof ProviderError?e.retryable:false});if(error)throw error;return data;}
export async function getVerifiedThemeCensusStatus(){const [{data:gate,error:ge},{data:batches,error:be},{data:proof,error:pe}]=await Promise.all([supabaseAdmin.from('verified_theme_census_gate_v7').select('*').maybeSingle(),supabaseAdmin.from('verified_theme_census_batches_v7').select('status'),supabaseAdmin.from('current_verified_theme_analysis_proof_v8').select('*').maybeSingle()]);if(ge)throw ge;if(be)throw be;if(pe)throw pe;const counts:Record<string,number>={};for(const b of batches||[]){const s=text(b.status)||'unknown';counts[s]=(counts[s]||0)+1;}return{gate,batches:counts,analysis_proof:proof};}
export async function runVerifiedThemeCensusWorkerStep(){const enq=await enqueue();if(enq.blocked)return{stage:'blocked',reason:'verified_theme_candidates_required',external_calls:0};const job=await claim();if(!job){const {data:gate,error}=await supabaseAdmin.from('verified_theme_census_gate_v7').select('*').maybeSingle();if(error)throw error;if(gate?.census_gate==='passed'){const {data:proof,error:proofErr}=await supabaseAdmin.rpc('record_verified_theme_analysis_proof_v8');if(proofErr)throw proofErr;return{stage:'theme_analysis_sealed',analysis_proof_receipt_id:proof,external_calls:0};}return{stage:'idle',batch_count:enq.count,external_calls:0};}
  let calls=0;try{const input=await getInput(job);const ms=models();const model=job.pass==='mapper'?ms.mapper:ms.critic;calls=1;const r=await callJson(model,instructions(job.pass),JSON.stringify({task:'full_candidate_census_on_verified_articles',pass_kind:job.pass,candidates:input.candidates,articles:input.articles}));const result=validate(r.value,input.articles,input.candidates);const saved=await store(job,model,r,result);return{stage:'theme_census_pass',run_id:job.runId,batch_id:job.id,pass_kind:job.pass,result:saved,external_calls:calls};}catch(e){const saved=await fail(job,e);return{stage:'theme_census_failed',run_id:job.runId,batch_id:job.id,pass_kind:job.pass,error:errMsg(e),result:saved,external_calls:calls};}
}
